### ISSUE TITLE
Comparison to Iron

### ISSUE THREAD

**Issue by DamianReeves** [kitlangton/neotype#40]
From an implementation, feature, roadmap, and project charter standpoint, how would you compare this to [Iron](https://github.com/Iltotore/iron)?

**Comment by kitlangton** [comment]
I actually just enabled discussion, so feel free to post further questions there if you'd like. 😊 

As to the question at hand, there are a couple of important differences: 

Firstly, **Neotype** is not merely a refined type library, but it is also a newtype library. So, you get newtypes plus the optional ability to refine their contents. I did this because newtypes and refined types are often used together, and it can be somewhat awkward to combine them when they are provided by two separate libraries. 

Secondly, the refined type syntax in libraries like `refined` and `iron` requires a type-level syntax for describing these refinements. Here's an Iron example:

```scala
type Password = (Match["[A-Za-z].*[0-9]|[0-9].*[A-Za-z]"] & MinLength[6] & MaxLength[20]) DescribedAs
  "Password must contain at least a letter, a digit and have a length between 6 and 20"
  
case class User(password: String :| Password) 
```

Neotype, on the other hand, allows you to write arbitrary Scala expressions with plain old Scala data types and methods:

```scala
type Password = Password.Type
object Password extends Newtype[String]:
  override inline def validate(input: String): Boolean =
    input.matches(".*([A-Za-z].*[0-9]|[0-9].*[A-Za-z]).*") 
      && input.length >= 6 
      && input.length <= 20
      
case class User(password: Password)  
```
